// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qumnlljgnqqajdslabvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1bW5sbGpnbnFxYWpkc2xhYnZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDQ1NDcsImV4cCI6MjA2NDE4MDU0N30.EoWhcu3YEnQ0_X16grrppmLtJ2SAWDh2fUWXM1IcnWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);